ROLE_DESCRIPTIONS = {
    'acrobat': 'Each night*, if either good living neighbour is drunk or poisoned, you die.',
    'al-hadikhia': 'Each night*, choose 3 players (all players learn who): each silently chooses to live or die, but if all live, all die.',
    'alchemist': 'You have a not-in-play Minion ability.',
    'amnesiac': 'You do not know what your ability is. Each day, privately guess what it is: you learn how accurate you are.',
    'apprentice': 'On your 1st night, you gain a Townsfolk ability (if good), or a Minion ability (if evil).',
    'artist': 'Once per game, during the day, privately ask the Storyteller any yes/no question.',
    'assassin': 'Once per game, at night*, choose a player: they die, even if for some reason they could not.',
    'atheist': 'The Storyteller can break the game rules & if executed, good wins, even if you are dead. [No evil characters]',
    'balloonist': 'Each night, you learn 1 player of each character type, until there are no more types to learn. [+1 Outsider]',
    'banshee': 'If the Demon kills you, all players learn this. From now on, you may nominate twice per day and vote twice per nomination.',
    'barber': 'If you died today or tonight, the Demon may choose 2 players (not another Demon) to swap characters.',
    'barista': 'Each night, until dusk, 1) a player becomes sober, healthy and gets true info, or 2) their ability works twice. They learn which.',
    'baron': 'There are extra Outsiders in play. [+2 Outsiders]',
    'beggar': 'You must use a vote token to vote. Dead players may choose to give you theirs. If so, you learn their alignment. You are sober & healthy.',
    'bishop': 'Only the Storyteller can nominate. At least 1 opposite player must be nominated each day.',
    'bone collector': 'Once per game, at night, choose a dead player: they regain their ability until dusk.',
    'boomdandy': 'If you are executed, all but 3 players die. 1 minute later, the player with the most players pointing at them dies.',
    'bounty hunter': 'You start knowing 1 evil player. If the player you know dies, you learn another evil player tonight. [1 Townsfolk is evil]',
    'bureaucrat': 'Each night, choose a player (not yourself): their vote counts as 3 votes tomorrow.',
    'butcher': 'Each day, after the 1st execution, you may nominate again.',
    'butler': 'Each night, choose a player (not yourself): tomorrow, you may only vote if they are voting too.',
    'cannibal': 'You have the ability of the recently killed executee. If they are evil, you are poisoned until a good player dies by execution.',
    'cerenovus': 'Each night, choose a player & a good character: they are “mad” they are this character tomorrow, or might be executed.',
    'chambermaid': 'Each night, choose 2 alive players (not yourself): you learn how many woke tonight due to their ability.',
    'chef': 'You start knowing how many pairs of evil players there are.',
    'choirboy': 'If the Demon kills the King, you learn which player is the Demon. [+ the King]',
    'clockmaker': 'You start knowing how many steps from the Demon to its nearest Minion.',
    'courtier': 'Once per game, at night, choose a character: they are drunk for 3 nights & 3 days.',
    'cult leader': 'Each night, you become the alignment of an alive neighbour. If all good players choose to join your cult, your team wins.',
    'damsel': 'All Minions know you are in play. If a Minion publicly guesses you (once), your team loses.',
    'deviant': 'If you were funny today, you cannot die by exile.',
    "devil's advocate": "Each night, choose a living player (different to last night): if executed tomorrow, they don't die.",
    'dreamer': 'Each night, choose a player (not yourself or Travellers): you learn 1 good and 1 evil character, 1 of which is correct.',
    'drunk': 'You do not know you are the Drunk. You think you are a Townsfolk character, but you are not.',
    'empath': 'Each night, you learn how many of your 2 alive neighbours are evil.',
    'engineer': 'Once per game, at night, choose which Minions or which Demon is in play.',
    'evil twin': "You & an opposing player know each other. If the good player is executed, evil wins. Good can't win if you both live.",
    'exorcist': "Each night*, choose a player (different to last night): the Demon, if chosen, learns who you are then doesn't wake tonight.",
    'fang gu': 'Each night*, choose a player: they die. The 1st Outsider this kills becomes an evil Fang Gu & you die instead. [+1 Outsider]',
    'farmer': 'If you die at night, an alive good player becomes a Farmer.',
    'fearmonger': 'Each night, choose a player. If you nominate & execute them, their team loses. All players know if you choose a new player.',
    'fisherman': 'Once per game, during the day, visit the Storyteller for some advice to help you win.',
    'flowergirl': 'Each night*, you learn if a Demon voted today.',
    'fool': "The first time you die, you don't.",
    'fortune teller': 'Each night, choose 2 players: you learn if either is a Demon. There is a good player that registers as a Demon to you.',
    'gambler': 'Each night*, choose a player & guess their character: if you guess wrong, you die.',
    'gangster': 'Once per day, you may choose to kill an alive neighbour, if your other alive neighbour agrees.',
    'general': 'Each night, you learn which alignment the Storyteller believes is winning: good, evil, or neither.',
    'goblin': 'If you publicly claim to be the Goblin when nominated & are executed that day, your team wins.',
    'godfather': 'You start knowing which Outsiders are in play. If 1 died today, choose a player tonight: they die. [−1 or +1 Outsider]',
    'golem': 'You may only nominate once per game. When you do, if the nominee is not the Demon, they die.',
    'goon': 'Each night, the 1st player to choose you with their ability is drunk until dusk. You become their alignment.',
    'gossip': 'Each day, you may make a public statement. Tonight, if it was true, a player dies.',
    'grandmother': 'You start knowing a good player & their character. If the Demon kills them, you die too.',
    'gunslinger': 'Each day, after the 1st vote has been tallied, you may choose a player that voted: they die.',
    'harlot': 'Each night*, choose a living player: if they agree, you learn their character, but you both might die.',
    'harpy': 'Each night, choose 2 players: tomorrow, the 1st player is mad that the 2nd is evil, or both might die.',
    'hatter': 'If you died today or tonight, the Minion & Demon players may choose new Minion & Demon characters to be.',
    'heretic': 'Whoever wins, loses & whoever loses, wins, even if you are dead.',
    'high priestess': 'Each night, learn which player the Storyteller believes you should talk to most.',
    'huntsman': 'Once per game, at night, choose a living player: the Damsel, if chosen, becomes a not-in-play Townsfolk. [+the Damsel]',
    'imp': 'Each night*, choose a player: they die. If you kill yourself this way, a Minion becomes the Imp.',
    'innkeeper': "Each night*, choose 2 players: they can't die tonight, but 1 is drunk until dusk.",
    'investigator': 'You start knowing that 1 of 2 players is a particular Minion.',
    'judge': 'Once per game, if another player nominated, you may choose to force the current execution to pass or fail.',
    'juggler': "On your 1st day, publicly guess up to 5 players' characters. That night, you learn how many you got correct.",
    'kazali': 'Each night*, choose a player: they die. [You choose which players are Minions. -? to +? Outsiders]',
    'king': 'Each night, if the dead outnumber the living, you learn 1 alive character. The Demon knows who you are.',
    'klutz': 'When you learn that you died, publicly choose 1 alive player: if they are evil, your team loses.',
    'knight': 'You start knowing 2 players that are not the Demon.',
    'legion': 'Each night*, a player might die. Executions fail if only evil voted. You register as a Minion too. [Most players are Legion]',
    'leviathan': 'If more than 1 good player is executed, you win. All players know you are in play. After day 5, evil wins.',
    'librarian': 'You start knowing that 1 of 2 players is a particular Outsider. (Or that zero are in play.)',
    "lil' monsta": 'Each night, Minions choose who babysits Lil\' Monsta\'s token & "is the Demon". A player dies each night*. [+1 Minion]',
    'lleech': 'Each night*, choose a player: they die. You start by choosing an alive player: they are poisoned - you die if & only if they die.',
    'lunatic': 'You think you are a Demon, but you are not. The Demon knows who you are & who you choose at night.',
    'lycanthrope': 'Each night*, choose a living player: if good, they die, but they are the only player that can die tonight.',
    'magician': 'The Demon thinks you are a Minion. Minions think you are a Demon.',
    'marionette': 'You think you are a good character but you are not. The Demon knows who you are. [You neighbour the Demon]',
    'mastermind': 'If the Demon dies by execution (ending the game), play for 1 more day. If a player is then executed, their team loses.',
    'mathematician': "Each night, you learn how many players’ abilities worked abnormally (since dawn) due to another character's ability.",
    'matron': 'Each day, you may choose up to 3 sets of 2 players to swap seats. Players may not leave their seats to talk in private.',
    'mayor': 'If only 3 players live & no execution occurs, your team wins. If you die at night, another player might die instead.',
    'mephit': 'You start knowing a secret word. The 1st good player to say this word becomes evil that night.',
    'mezepheles': 'You start knowing a secret word. The 1st good player to say this word becomes evil that night.',
    'minstrel': 'When a Minion dies by execution, all other players (except Travellers) are drunk until dusk tomorrow.',
    'monk': 'Each night*, choose a player (not yourself): they are safe from the Demon tonight.',
    'moonchild': 'When you learn that you died, publicly choose 1 alive player. Tonight, if it was a good player, they die.',
    'mutant': 'If you are “mad” about being an Outsider, you might be executed.',
    'nightwatchman': 'Once per game, at night, choose a player: they learn who you are.',
    'no dashii': 'Each night*, choose a player: they die. Your 2 Townsfolk neighbours are poisoned.',
    'noble': 'You start knowing 3 players, 1 and only 1 of which is evil.',
    'ogre': "On your 1st night, choose a player (not yourself): you become their alignment (you don't know which) even if drunk or poisoned.",
    'ojo': 'Each night*, choose a character: they die. If they are not in play, the Storyteller chooses who dies.',
    'oracle': 'Each night*, you learn how many dead players are evil.',
    'organ grinder': 'All players keep their eyes closed when voting & the vote tally is secret. Votes for you only count if you vote.',
    'pacifist': 'Executed good players might not die.',
    'philosopher': 'Once per game, at night, choose a good character: gain that ability. If this character is in play, they are drunk.',
    'pit-hag': 'Each night*, choose a player & a character they become (if not-in-play). If a Demon is made, deaths tonight are arbitrary.',
    'pixie': 'You start knowing 1 in-play Townsfolk. If you were mad that you were this character, you gain their ability when they die.',
    'plague doctor': 'If you die, the Storyteller gains a not-in-play Minion ability.',
    'po': 'Each night*, you may choose a player: they die. If your last choice was no-one, choose 3 players tonight.',
    'poisoner': 'Each night, choose a player: they are poisoned tonight and tomorrow day.',
    'politician': 'If you were the player most responsible for your team losing, you change alignment & win, even if dead.',
    'poppy grower': 'Minions & Demons do not know each other. If you die, they learn who each other are that night.',
    'preacher': 'Each night, choose a player: a Minion, if chosen, learns this. All chosen Minions have no ability.',
    'professor': 'Once per game, at night*, choose a dead player: if they are a Townsfolk, they are resurrected.',
    'psychopath': 'Each day, before nominations, you may publicly choose a player: they die. If executed, you only die if you lose roshambo.',
    'pukka': 'Each night, choose a player: they are poisoned. The previously poisoned player dies then becomes healthy.',
    'puzzlemaster': '1 player is drunk, even if you die. If you guess (once) who it is, learn the Demon player, but guess wrong & get false info.',
    'ravenkeeper': 'If you die at night, you are woken to choose a player: you learn their character.',
    'recluse': 'You might register as evil & as a Minion or Demon, even if dead.',
    'riot': 'Nominees die, but may nominate again immediately (on day 3, they must). After day 3, evil wins. [All Minions are Riot]',
    'sage': 'If the Demon kills you, you learn that it is 1 of 2 players.',
    'sailor': "Each night, choose an alive player: either you or they are drunk until dusk. You can't die.",
    'saint': 'If you die by execution, your team loses.',
    'savant': 'Each day, you may visit the Storyteller to learn 2 things in private: 1 is true & 1 is false.',
    'scapegoat': 'If a player of your alignment is executed, you might be executed instead.',
    'scarlet woman': 'If there are 5 or more players alive & the Demon dies, you become the Demon. (Travellers don’t count)',
    'seamstress': 'Once per game, at night, choose 2 players (not yourself): you learn if they are the same alignment.',
    'shabaloth': 'Each night*, choose 2 players: they die. A dead player you chose last night might be regurgitated.',
    'shugenja': 'You start knowing if your closest evil player is clockwise or anti-clockwise. If equidistant, this info is arbitrary.',
    'slayer': 'Once per game, during the day, publicly choose a player: if they are the Demon, they die.',
    'snake charmer': 'Each night, choose an alive player: a chosen Demon swaps characters & alignments with you & is then poisoned.',
    'snitch': 'Minions start knowing 3 not-in-play characters.',
    'soldier': 'You are safe from the Demon.',
    'spy': 'Each night, you see the Grimoire. You might register as good & as a Townsfolk or Outsider, even if dead.',
    'steward': 'You start knowing 1 good player.',
    'summoner': 'You get 3 bluffs. On the 3rd night, choose a player: they become an evil Demon of your choice. [No Demon]',
    'sweetheart': 'When you die, 1 player is drunk from now on.',
    'tea lady': "If both your alive neighbours are good, they can't die.",
    'thief': 'Each night, choose a player (not yourself): their vote counts negatively tomorrow.',
    'tinker': 'You might die at any time.',
    'town crier': 'Each night*, you learn if a Minion nominated today.',
    'undertaker': 'Each night*, you learn which character died by execution today.',
    'vigormortis': 'Each night*, choose a player: they die. Minions you kill keep their ability & poison 1 Townsfolk neighbour. [−1 Outsider]',
    'village idiot': 'Each night, choose a player: you learn their alignment. [+0 to +2 Village Idiots. 1 of the extras is drunk]',
    'virgin': 'The 1st time you are nominated, if the nominator is a Townsfolk, they are executed immediately.',
    'vizier': 'All players know who you are. You can not die during the day. If good voted, you may choose to execute immediately.',
    'vortox': 'Each night*, choose a player: they die. Townsfolk abilities yield false info. Each day, if no-one is executed, evil wins.',
    'voudon': "Only you and the dead can vote. They don't need a vote token to do so. A 50% majority is not required.",
    'washerwoman': 'You start knowing that 1 of 2 players is a particular Townsfolk.',
    'widow': 'On your 1st night, look at the Grimoire and choose a player: they are poisoned. 1 good player knows a Widow is in play.',
    'witch': 'Each night, choose a player: if they nominate tomorrow, they die. If just 3 players live, you lose this ability.',
    'yaggababble': 'You start knowing a secret phrase. For each time you said it publicly today, a player might die.',
    'zombuul': 'Each night*, if no-one died today, choose a player: they die. The 1st time you die, you live but register as dead.',
}
